### ISSUE TITLE
module type error, ES modules vs CommonJS

### ISSUE THREAD

**Issue by Gideon-Felt** [GillesZunino/insomnia-plugin-azure-ad-authentication#8]
`Error: require() of ES Module C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\node_modules\@azure\msal-node\dist\index.js from C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\dist\index.js not supported.
C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\node_modules\@azure\msal-node\dist\index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\node_modules\@azure\msal-node\dist\index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\node_modules\@azure\msal-node\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at Module._extensions..js (node:internal/modules/cjs/loader:1297:19)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\dist\index.js:1:617
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\dist\index.js:1:50495)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\Insomnia\plugins\insomnia-plugin-azure-ad-authentication\dist\index.js:2:3)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at q$ (file:///C:/Users/username/AppData/Local/insomnia/app-2023.5.7/resources/app.asar/index-7770d3c9.js:57:7484)
    at $C (file:///C:/Users/username/AppData/Local/insomnia/app-2023.5.7/resources/app.asar/index-7770d3c9.js:57:8229)
    at async u (file:///C:/Users/username/AppData/Local/insomnia/app-2023.5.7/resources/app.asar/index-7770d3c9.js:193:33449)`

**Comment by GillesZunino** [comment]
Should be fixed in v0.0.17 - Tried with Insomnia 2023.5.7
